# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420854b7649bdec2029f857fede13e885ce823697fabb726fbd8a029c382efdce943056809e683de9fa1981d780a773fee58b569d2df48e3e8386126a911de2e

test:
  secret_key_base: 633ca8f305026c05c69b889902cb729c63f2dea9ee5d1de4fb33a3391cbfcaf34e8450ebead0c6ac286803816a18e785ba51ca3aad4819f3d7c66996206470ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
